---
namespace: no-as-a-service

resources:
- ../../base

patches:
  - target:
      kind: Route
      name: no-as-a-service
    patch: |-
      - op: replace
        path: /spec/host
        value: "no-as-a-service.apps.ocp4.pcfe.net"

